#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	blur_radius=9.0
	active_color=0xffa5a5a5
	inactive_color=0x00000000
	blacklist="pycharm,TickTick,CleanMyMac X"
	# whitelist="Arc,iTerm2,Obsidian,Zed,Sublime Text,Skim,Preview,TickTick,IINA"
)

borders "${options[@]}"
