set -g default-terminal "screen-256color"
set -g prefix C-b
bind-key C-b send-prefix
bind-key x kill-pane

unbind %
bind _ split-window -h

unbind '"'
bind - split-window -v

bind p previous-window

bind n next-window

bind ) switch-client -n

bind ( switch-client -p

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

unbind c 
bind o new-window

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind Up
unbind Down
unbind Left
unbind Right

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5
bind -r m resize-pane -Z

set -g mouse on
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse
# usage
set -g status-interval 2
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# myoption
set-option -g status-position bottom
set-option -sg escape-time 10
set-option -g automatic-rename on
# set-option -g status-style bg=black,fg=brightgreen
# set-option -g status-right '#(~/tmux-powerline/tmux-powerline/powerline.sh right)'
bind-key W if-shell '[ $(tmux list-sessions | wc -l) -ne 1 ]' \
                    "run-shell 'tmux switch-client -n \\\; kill-session -t \"#S\"'" \
                    "run-shell 'tmux kill-session -t \"#S\"'"
bind s command-prompt -p "New Session:" "new-session -A -s '%%'"
# tpm plugin

########################################################################################################################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'

set-option -g status-right "#{cpu_fg_color}#{cpu_icon} #{cpu_percentage} #{ram_fg_color}#{ram_icon} #{ram_percentage}"
run '~/.tmux/plugins/tpm/tpm'
########################################################################################################################

#status-bar
set -g status-position bottom
set -g status-style bg=default
set -g status-fg white
set-option -g status-justify left
set-option -g status-interval 5
set-option -g status-right-length 80
set-option -g status-left-length 20
set-option -g window-status-current-format '#[bold] #{window_index}:#{window_name}#{window_flags}'
set-option -g window-status-format '#{window_index}:#{window_name}#{window_flags}'
set-option -g status-left '#[fg=default][#{session_name}] '
set-option -g status-interval 1
