#!/bin/zsh

FONT="SF Pro:Bold:13"

bar=(
  height=40
  border_width=0
  shadow=off
  position=bottom
  sticky=on
  padding_left=9
  padding_right=9
  y_offset=-7
  margin=20
  topmost=true
  color=0x00000000
)

bottombar --bar "${bar[@]}"

source "item.sh"

bottombar --update

echo "bottombar configuration loaded.."
