#!/bin/bash

# Source colors
source "$CONFIG_DIR/colors.sh"

# Global bar settings
sketchybar --bar \
           height=14 \
           color=$BAR_COLOR \
           padding_left=5 \
           padding_right=5 \
           blur_radius=0 \
           position=bottom \
           margin=0 \
           sticky=on \
           topmost=on

# Defaults
sketchybar --default \
           label.color=$LABEL_COLOR \
           label.font="JetBrainsMono Nerd Font:ExtraBold:12.0" \
           icon.color=$GREY \
           icon.font="JetBrainsMono Nerd Font:Regular:12.0" \
           padding_left=5 \
           padding_right=5 \
           label.padding_left=2 \
           label.padding_right=2 \
           label.y_offset=-1 \
           icon.y_offset=-1

# Aerospace space list & Window count (left)
source "$CONFIG_DIR/items/aerospace.sh"

# Network status (left)
sketchybar --add item network left \
           --set network update_freq=1 \
           script="$CONFIG_DIR/plugins/network.sh" \
           padding_left=15

# Right section items
sketchybar --add item time right \
           --set time icon="" \
           update_freq=60 \
           script="$CONFIG_DIR/plugins/time.sh"

sketchybar --add item battery right \
            --set battery icon="󰁹" \
            update_freq=30 \
            updates=on \
            script="$CONFIG_DIR/plugins/battery.sh" \
            --subscribe battery power_source_change system_woke

sketchybar --add item swap right \
           --set swap icon="󰈔" \
           update_freq=10 \
           script="$CONFIG_DIR/plugins/swap.sh"

sketchybar --add item ram right \
           --set ram icon="󰍛" \
           update_freq=10 \
           script="$CONFIG_DIR/plugins/ram.sh"

sketchybar --add item cpu right \
           --set cpu icon="󰻠" \
           update_freq=5 \
           script="$CONFIG_DIR/plugins/cpu.sh"

sketchybar --update
