live_config_reload = true

[mouse]
  hide_when_typing = true

[window]
  option_as_alt = "Both"
  opacity = 0.95
  padding ={ x = 25 , y = 15 }
  dynamic_padding = false
  decorations = "Buttonless"
  startup_mode = "Maximized"
  blur = true

[font]
  normal = {family = "JetBrainsMono Nerd Font",style = "SemiBold"}
  offset.x = 0
  offset.y = 2
  size = 17.0

[cursor]
  blink_timeout = 0
  blink_interval = 400
  style = {blinking = "Always"}

# import = [
#   "~/.config/alacritty/themes/themes/base16_default_dark.yaml"
# ]

[keyboard]
bindings = [
  # tmux
   { key = "A", mods = "Command", chars = "ta\n" },
   { key = "K", mods = "Command", chars = "\u0005k" },
   { key = "LBracket", mods = "Command", chars = "\u0005[" },
   { key = "RBracket", mods = "Command", chars = "\u0005]" },
   { key = "W", mods = "Command", chars = "\u0005q" },
   { key = "T", mods = "Command", chars = "\u0005t" },
   { key = "N", mods = "Command|Control", chars = "\u0005n" },
   { key = "P", mods = "Command|Control", chars = "\u0005p" },

   { key = "Minus", mods = "Command|Shift", chars = "\u0005-" },
   { key = "Backslash", mods = "Command|Shift", chars = "\u0005|" },

   { key = "D", mods = "Command", chars = "\u0005d" },
   { key = "D", mods = "Command|Shift", chars = "\u0005W" },
   { key = "P", mods = "Command", chars = "\u0002w" },
   { key = "E", mods = "Command", chars = "\u0003T" },
   { key = "G", mods = "Command", chars = "\u0005[" },
   { key = "N", mods = "Command|Shift", chars = "\u0005s" },
   { key = "R", mods = "Command", chars = "\u0005r" },
]
